site_name: lab-edu 文档中心
site_description: 文档中心 — 汇集系统架构、API 与部署 / 使用指南，助力快速上手与团队协作
repo_url: https://github.com/lab-edu/docs

theme:
  name: terminal
  language: zh
  features:
    - footer.prev_next

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/highlight.min.js
  - https://unpkg.com/highlightjs-cobol/dist/cobol.min.js
  - hl.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/styles/a11y-light.min.css

nav:
  - Home: index.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: " #"
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs
